# Generated by Django 4.2 on 2023-05-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_style_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style_way',
            field=models.CharField(choices=[('S', 'All'), ('A', 'Aristrocratic'), ('I', 'Imaginative'), ('F', 'Futuristic'), ('B', 'Brutalistic'), ('M', 'Minimalistic')], default='S', max_length=1),
        ),
    ]
