# Generated by Django 4.2 on 2023-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style_way',
            field=models.CharField(choices=[('A', 'Aristrocratic'), ('I', 'Imaginative'), ('F', 'Futuristic'), ('B', 'Brutalistic'), ('S', 'Simplistic')], default='S', max_length=1),
        ),
    ]
