# Generated by Django 4.2 on 2023-05-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='style_sign',
            field=models.CharField(default='', max_length=1),
        ),
    ]
