# Generated by Django 4.2 on 2023-05-25 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_creations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creations',
            new_name='Creation',
        ),
    ]
