# Generated by Django 4.2 on 2023-05-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_creation_image_generateditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creation',
        ),
    ]
