# Generated by Django 4.2 on 2023-05-26 08:42

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateditem',
            name='image',
            field=models.ImageField(upload_to=store.models.generated_file_path),
        ),
    ]
