# Generated by Django 4.2 on 2023-05-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_generateditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, help_text='0=default, 1=Subscribed'),
        ),
    ]
