# Generated by Django 4.2 on 2023-06-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_product_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=150)),
                ('lname', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=150)),
                ('address_info', models.TextField(max_length=150, null=True)),
                ('postal_code', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(choices=[('Deutschland', 'Germany'), ('Österreich', 'Austria'), ('Schweiz', 'Switzerland')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.profile')),
            ],
        ),
    ]
